# Pandas Challenges :-

### Data Loading 
 Load a CSV or Excel file into a pandas DataFrame and explore the basic information about the dataset

In [1]:
import pandas as pd
import numpy as np

In [3]:
gendf = pd.read_csv("genshin.csv",encoding='latin1')

In [4]:
gendf

,character_name,rarity,region,vision,weapon_type,model,constellation,birthday,special_dish,affiliation,...,hp_1_20,atk_1_20,def_1_20,spsecial_0,special_1,special_2,special_3,special_4,special_5,special_6
0,Albedo,5,Mondstadt,Geo,Sword,Medium Male,Princeps Cretaceus,13-Sep,Woodland Dream,Knights of Favonius,...,1030,20,68,0.0%,0.0%,7.2%,14.4%,14.4%,21.6%,28.8%
1,Alhaitham,5,Sumeru,Dendro,Sword,Tall Male,Vultur Volans,11-Feb,Ideal Circumstance,Sumeru Akademiya,...,1039,24,60,0.0%,0.0%,7.2%,14.4%,14.4%,21.6%,28.8%
2,Aloy,5,NaN,Cryo,Bow,Medium Female,Nora Fortis,4-Apr,Satiety Gel,Wandering Heroine,...,848,18,53,0.0%,0.0%,7.2%,14.4%,14.4%,21.6%,28.8%
3,Amber,4,Mondstadt,Pyro,Bow,Medium Female,Lepus,10-Aug,Outrider's Champion Steak!,Knights of Favonius,...,793,19,50,0.0%,0.0%,6.0%,12.0%,12.0%,18.0%,24.0%
4,Arataki Itto,5,Inazuma,Geo,Claymore,Tall Male,Taurus Iracundus,1-Jun,Way of the Strong,Arataki Gang,...,1001,18,75,0.0%,0.0%,4.8%,9.6%,9.6%,14.4%,19.2%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Yaoyao,4,Liyue,Dendro,Polearm,Short Female,Osmanthus,6-Mar,Qingce Household Dish,Streetward Rambler's Abode,...,1030,17,62,0.0%,0.0%,6.0%,12.0%,12.0%,18.0%,24.0%
68,Yelan,5,Liyue,Hydro,Bow,Tall Female,Umbrabilis Orchis,20-Apr,Dew-Dipped Shrimp,Yanshang Teahouse,...,1125,19,43,0.0%,0.0%,4.8%,9.6%,9.6%,14.4%,19.2%
69,Yoimiya,5,Inazuma,Pyro,Bow,Medium Female,Carassius Auratus,21-Jun,Summer Festival Fish,Naganohara Fireworks,...,791,25,48,0.0%,0.0%,4.8%,9.6%,9.6%,14.4%,19.2%
70,Yun Jin,4,Liyue,Geo,Polearm,Medium Female,Opera Grandis,21-May,Cloud-Shrouded Jade,Yun-Han Opera House,...,894,16,62,0.0%,0.0%,6.7%,13.3%,13.3%,20.0%,26.7%
71,Zhongli,5,Liyue,Geo,Polearm,Tall Male,Lapis Dei,31-Dec,Slow-Cooked Bamboo Shoot Soup,Liyue Harbor,...,1144,20,57,0.0%,0.0%,7.2%,14.4%,14.4%,21.6%,28.8%

In [5]:
gendf.describe()

,rarity,hp_90_90,atk_90_90,def_90_90,hp_80_90,atk_80_90,def_80_90,hp_80_80,atk_80_80,def_80_80,...,def_40_40,hp_20_40,atk_20_40,def_20_40,hp_20_20,atk_20_20,def_20_20,hp_1_20,atk_1_20,def_1_20
count,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,...,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000
mean,4.500000,11717.055556,248.347222,702.958333,11024.402778,230.986111,653.944444,10360.680556,219.541667,621.583333,...,288.763889,3202.194444,67.763889,192.111111,2443.416667,51.736111,146.638889,947.847222,19.777778,56.680556
std,0.503509,1647.876798,52.213581,95.662028,1940.139778,48.410362,88.928186,1445.054293,45.789149,84.304069,...,38.056109,424.308473,13.468265,25.541767,310.539093,10.123175,19.337846,118.948878,3.712264,7.531766
min,4.000000,9189.000000,106.000000,499.000000,8553.000000,99.000000,464.000000,8144.000000,94.000000,440.000000,...,200.000000,2555.000000,29.000000,134.000000,1978.000000,21.000000,100.000000,763.000000,8.000000,38.000000
25%,4.000000,10352.750000,212.000000,629.500000,9627.250000,198.000000,584.750000,9148.250000,188.000000,556.000000,...,259.000000,2794.500000,59.000000,169.000000,2108.000000,46.000000,129.000000,820.750000,18.000000,50.000000
50%,4.500000,11908.000000,234.000000,705.500000,11083.000000,217.000000,656.500000,10553.000000,207.000000,625.000000,...,294.000000,3309.500000,64.000000,195.000000,2514.000000,49.000000,148.000000,983.500000,19.000000,57.000000
75%,5.000000,12925.500000,297.250000,769.500000,12017.000000,276.250000,715.750000,11404.250000,262.250000,679.500000,...,315.000000,3479.750000,80.000000,210.250000,2652.750000,60.000000,161.000000,1030.000000,22.250000,62.000000
max,5.000000,15674.000000,349.000000,959.000000,21080.000000,325.000000,892.000000,13829.000000,308.000000,846.000000,...,386.000000,4211.000000,94.000000,258.000000,3165.000000,79.000000,194.000000,1220.000000,27.000000,75.000000

In [9]:
ds = gendf.sort_values(by="rarity" ,ascending=False)
ds[['character_name','rarity']]

        character_name  rarity
0               Albedo       5
49  Sangonomiya Kokomi       5
28      Kamisato Ayato       5
30              Keqing       5
32                Klee       5
..                 ...     ...
43           Ningguang       4
44              Noelle       4
15               Diona       4
47               Razor       4
36                Lisa       4

[72 rows x 2 columns]

In [12]:
ds.to_csv('genshinCharBYRare.csv')

In [16]:
 ds[ds['vision'] == 'Hydro']

,character_name,rarity,region,vision,weapon_type,model,constellation,birthday,special_dish,affiliation,...,hp_1_20,atk_1_20,def_1_20,spsecial_0,special_1,special_2,special_3,special_4,special_5,special_6
49,Sangonomiya Kokomi,5,Inazuma,Hydro,Catalyst,Medium Female,Dracanea Somnolenta,22-Feb,A Stunning Stratagem,Watatsumi Island,...,1049,18,51,0.0%,0.0%,7.2%,14.4%,14.4%,21.6%,28.8%
28,Kamisato Ayato,5,Inazuma,Hydro,Sword,Tall Male,Cypressus Custos,26-Mar,Quiet Elegance,Yashiro Commission,...,1068,24,60,0.0%,0.0%,9.6%,19.2%,19.2%,28.8%,38.4%
40,Mona,5,Mondstadt,Hydro,Catalyst,Medium Female,Astrolabos,31-Aug,Der Weisheit Letzter Schluss (Life),Mondstadt,...,810,22,51,0.0%,0.0%,8.0%,16.0%,16.0%,24.0%,32.0%
42,Nilou,5,Sumeru,Hydro,Sword,Medium Female,Lotos Somno,3-Dec,Swirling Steps,Zubayr Theater,...,1182,17,56,0.0%,0.0%,7.2%,14.4%,14.4%,21.6%,28.8%
54,Tartaglia,5,Snezhnaya,Hydro,Bow,Tall Male,Monoceros Caeli,20-Jul,A Prize Catch,Fatui,...,1020,23,63,0.0%,0.0%,7.2%,14.4%,14.4%,21.6%,28.8%
68,Yelan,5,Liyue,Hydro,Bow,Tall Female,Umbrabilis Orchis,20-Apr,Dew-Dipped Shrimp,Yanshang Teahouse,...,1125,19,43,0.0%,0.0%,4.8%,9.6%,9.6%,14.4%,19.2%
9,Candace,4,Sumeru,Hydro,Polearm,Tall Female,Sagitta Scutum,3-May,Utmost Care,Aaru Village,...,911,17,57,0.0%,0.0%,6.0%,12.0%,12.0%,18.0%,24.0%
6,Barbara,4,Mondstadt,Hydro,Catalyst,Medium Female,Crater,5-Jul,Spicy Stew,Church of Favonius,...,821,13,56,0.0%,0.0%,6.0%,12.0%,12.0%,18.0%,24.0%
63,Xingqiu,4,Liyue,Hydro,Sword,Medium Male,Fabulae Textile,9-Oct,All-Delicacy Parcels,Feiyun Commerce Guild,...,857,17,64,0.0%,0.0%,6.0%,12.0%,12.0%,18.0%,24.0%

In [18]:
gendf.sort_values(by="def_1_20", ascending=False)

,character_name,rarity,region,vision,weapon_type,model,constellation,birthday,special_dish,affiliation,...,hp_1_20,atk_1_20,def_1_20,spsecial_0,special_1,special_2,special_3,special_4,special_5,special_6
4,Arataki Itto,5,Inazuma,Geo,Claymore,Tall Male,Taurus Iracundus,1-Jun,Way of the Strong,Arataki Gang,...,1001,18,75,0.0%,0.0%,4.8%,9.6%,9.6%,14.4%,19.2%
45,Qiqi,5,Liyue,Cryo,Sword,Short Female,Pristina Nova,3-Mar,No Tomorrow,Bubu Pharmacy,...,963,22,72,0.0%,0.0%,5.5%,11.1%,11.1%,16.6%,22.2%
0,Albedo,5,Mondstadt,Geo,Sword,Medium Male,Princeps Cretaceus,13-Sep,Woodland Dream,Knights of Favonius,...,1030,20,68,0.0%,0.0%,7.2%,14.4%,14.4%,21.6%,28.8%
23,Hu Tao,5,Liyue,Pyro,Polearm,Medium Female,Papilio Charontis,15-Jul,Ghostly March,Wangsheng Funeral Parlor,...,1211,8,68,0.0%,0.0%,9.6%,19.2%,19.2%,28.8%,38.4%
44,Noelle,4,Mondstadt,Geo,Claymore,Medium Female,Parma Cordis,21-Mar,Lighter-Than-Air Pancake,Knights of Favonius,...,1012,16,67,0.0%,0.0%,7.5%,15.0%,15.0%,22.5%,30.0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,Kirara,4,Inazuma,Dendro,Sword,Medium Female,Arcella,22-Jan,Energizing Bento,Komaniya Express,...,1021,18,45,0.0%,0.0%,6.0%,12.0%,12.0%,18.0%,24.0%
65,Yae Miko,5,Inazuma,Electro,Catalyst,Tall Female,Divina Vulpes,27-Jun,Fukuuchi Udon,Grand Narukami Shrine,...,807,26,44,0.0%,0.0%,4.8%,9.6%,9.6%,14.4%,19.2%
68,Yelan,5,Liyue,Hydro,Bow,Tall Female,Umbrabilis Orchis,20-Apr,Dew-Dipped Shrimp,Yanshang Teahouse,...,1125,19,43,0.0%,0.0%,4.8%,9.6%,9.6%,14.4%,19.2%
38,Lyney,5,Fontaine,Pyro,Bow,Medium Male,Felis Fuscus,2-Feb,Cubic Tricks,Hotel Bouffes d'ete,...,857,24,41,0.0%,0.0%,4.8%,9.6%,9.6%,14.4%,19.2%
5,Baizhu,5,Liyue,Dendro,Catalyst,Tall Male,Lagenaria,25-Apr,Heat-Quelling Soup,Bubu Pharmacy,...,1039,14,38,0.0%,0.0%,7.2%,14.4%,14.4%,21.6%,28.8%

In [23]:
gendf[["character_name"]]

   character_name
0          Albedo
1       Alhaitham
2            Aloy
3           Amber
4    Arataki Itto
..            ...
67         Yaoyao
68          Yelan
69        Yoimiya
70        Yun Jin
71        Zhongli

[72 rows x 1 columns]

In [28]:
max_hp_index = gendf["hp_90_90"].idxmax()
character_with_highest_hp = gendf.loc[max_hp_index]
print(character_with_highest_hp)

character_name       Dehya
rarity                   5
region              Sumeru
vision                Pyro
weapon_type       Claymore
                    ...
special_2             7.2%
special_3            14.4%
special_4            14.4%
special_5            21.6%
special_6            28.8%
Name: 13, Length: 70, dtype: object

# Data Cleaning
Clean the data by handling missing values, removing duplicates, and converting data types

In [29]:
gendf.isnull().sum()

character_name    0
rarity            0
region            3
vision            2
weapon_type       0
                 ..
special_2         0
special_3         0
special_4         0
special_5         0
special_6         0
Length: 70, dtype: int64